FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY backend/ .
RUN dotnet restore "api/OpenTrainingPlatform.Api/OpenTrainingPlatform.Api.csproj"
RUN dotnet build "api/OpenTrainingPlatform.Api/OpenTrainingPlatform.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "api/OpenTrainingPlatform.Api/OpenTrainingPlatform.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OpenTrainingPlatform.Api.dll"]
